title: "Cases for {user}"
description: "Listing all cases associated with this member."
color: "0x3498DB"

author:
  name: "OGPB Moderation"
  icon_url: "https://avatars.githubusercontent.com/u/125516250?v=4"

thumbnail: "https://cdn.vectorstock.com/i/500p/45/59/profile-photo-placeholder-icon-design-in-gray-vector-37114559.jpg"  # optional placeholder

fields:
  - name: "Cases"
    value: "{cases}"
    inline: false

footer:
  text: "OGPB Moderation Bot"
