title: "Example"
description: "An example description!."
color: "0xE74C3C"

author:
  name: "OGPB Moderation"
  icon_url: "https://avatars.githubusercontent.com/u/125516250?v=4"

thumbnail: "https://cdn.vectorstock.com/i/500p/45/59/profile-photo-placeholder-icon-design-in-gray-vector-37114559.jpg"  # Optional user avatar placeholder
footer:
  text: "Example"

fields:
  - name: "Example"
    value: "123"
    inline: false
