# role id: level
levels:
  "0": 0

# type: channel id
log_channels:
  moderation: ""

command_overrides:
  command_name:
    permission:
      - "permission_name"
    role:
      - "role_id"
    level: 0  # minimum level
